"""Offline tests for the turn-scoped deterministic client_msg_id (TASK-114).

No network, no database: the key is a pure function, and that is the property under test. What
matters to a real candidate is that the same turn, regenerated by the catch-up timer after a failed
send, produces the SAME key -- the executor's ledger is what turns that into "sent once" rather than
"sent twice".
"""
import ast
import json
import pathlib
import subprocess
import sys

import pytest

from app.wa import bridge_ids as BI

ROOT = pathlib.Path(__file__).resolve().parents[1]
LEAD = "+491701234567"
OTHER = "+491709999999"
TURN = "wamid.HBgNNDkxNzAxMjM0NTY3FQIAEhgg"


def _key_in_a_fresh_interpreter(**kwargs):
    """The same call in a brand-new process, printed. Keys outlive restarts or they are not keys."""
    code = ("import json,sys;from app.wa import bridge_ids as BI;"
            "sys.stdout.write(BI.reply_key(**json.loads(sys.argv[1])))")
    proc = subprocess.run([sys.executable, "-c", code, json.dumps(kwargs)], cwd=ROOT,
                          capture_output=True, text=True)
    assert proc.returncode == 0, proc.stderr
    return proc.stdout


# --- the conversational key ------------------------------------------------------------------------

def test_the_same_turn_yields_the_same_key_in_a_new_process():
    """The failure chain this exists for crosses processes: the webhook worker fails the send, and
    pflege-wa-catchup.timer re-drives the turn three minutes later in a different interpreter."""
    kwargs = {"phone": LEAD, "turn_key": TURN, "action": "reply", "bubble_index": 0}
    assert BI.reply_key(**kwargs) == _key_in_a_fresh_interpreter(**kwargs)


def test_the_key_is_a_wab_o_prefix_and_32_hex_characters():
    key = BI.reply_key(phone=LEAD, turn_key=TURN, action="reply", bubble_index=0)
    assert key.startswith("wab.o.")
    digest = key[len("wab.o."):]
    assert len(digest) == 32 and all(ch in "0123456789abcdef" for ch in digest)


def test_each_bubble_of_one_turn_gets_its_own_key():
    """One bubble is one HTTP call: a two-bubble reply whose second bubble fails must not re-send
    the first, which only works if the two keys differ."""
    keys = [BI.reply_key(phone=LEAD, turn_key=TURN, action="reply", bubble_index=i) for i in range(3)]
    assert len(set(keys)) == 3


@pytest.mark.parametrize("changed", [
    {"phone": OTHER},
    {"turn_key": "wamid.DIFFERENT"},
    {"action": "media_ack"},
    {"bubble_index": 1},
])
def test_every_component_changes_the_key(changed):
    base = {"phone": LEAD, "turn_key": TURN, "action": "reply", "bubble_index": 0}
    assert BI.reply_key(**base) != BI.reply_key(**{**base, **changed})


def test_turn_key_has_no_default_and_must_be_passed_by_name():
    """On this rail there is no provider id to fall back on, so a defaulted turn_key would key two
    different conversations the same. Positional calls are refused for the same reason: turn_key and
    action are both strings, and swapping them would produce a plausible-looking wrong key."""
    with pytest.raises(TypeError):
        BI.reply_key(phone=LEAD, action="reply", bubble_index=0)
    with pytest.raises(TypeError):
        BI.reply_key(LEAD, TURN, "reply", 0)


@pytest.mark.parametrize("bad", [None, "", "   ", 42, " wamid.x"])
def test_an_unusable_turn_key_raises_instead_of_being_filled_in(bad):
    with pytest.raises(ValueError, match="turn_key"):
        BI.reply_key(phone=LEAD, turn_key=bad, action="reply", bubble_index=0)


def test_a_phone_that_is_not_e164_raises_rather_than_being_normalized():
    """Two spellings of one number would be two keys, i.e. two deliveries."""
    with pytest.raises(ValueError, match="canonicalize_phone"):
        BI.reply_key(phone="0170 1234567", turn_key=TURN, action="reply", bubble_index=0)


@pytest.mark.parametrize("bad", [-1, "0", 1.0, True])
def test_a_bubble_index_that_is_not_a_whole_count_raises(bad):
    with pytest.raises(ValueError, match="bubble_index"):
        BI.reply_key(phone=LEAD, turn_key=TURN, action="reply", bubble_index=bad)


# --- the campaign key ------------------------------------------------------------------------------

def test_the_campaign_key_is_the_natural_key_spelled_out():
    assert BI.campaign_key(campaign_id="pflege-okt-2026", phone=LEAD, attempt=2) == \
        "wab.o.camp.pflege-okt-2026." + LEAD + ".2"


def test_a_campaign_attempt_keeps_its_key_when_it_is_retried():
    """store.claim_campaign_send writes the attempt number before the POST, so a retry inside the
    same attempt re-posts the same key and the executor replays it instead of sending again."""
    first = BI.campaign_key(campaign_id="c1", phone=LEAD, attempt=1)
    assert BI.campaign_key(campaign_id="c1", phone=LEAD, attempt=1) == first
    assert BI.campaign_key(campaign_id="c1", phone=LEAD, attempt=2) != first


@pytest.mark.parametrize("kwargs", [
    {"campaign_id": "", "phone": LEAD, "attempt": 1},
    {"campaign_id": "c1", "phone": "01701234567", "attempt": 1},
    {"campaign_id": "c1", "phone": LEAD, "attempt": 0},
])
def test_an_unusable_campaign_component_raises(kwargs):
    with pytest.raises(ValueError):
        BI.campaign_key(**kwargs)


# --- no random component anywhere (TASK-114 AC#2) ---------------------------------------------------

def test_the_module_imports_nothing_that_could_vary_between_calls():
    """A single uuid4() or time.time() anywhere in the derivation would silently restore the bug the
    module exists to remove, and every test above would still pass on the first call."""
    tree = ast.parse((ROOT / "app" / "wa" / "bridge_ids.py").read_text(encoding="utf-8"))
    imported = {n.names[0].name.split(".")[0] for n in ast.walk(tree) if isinstance(n, ast.Import)}
    imported |= {n.module.split(".")[0] for n in ast.walk(tree) if isinstance(n, ast.ImportFrom) and n.module}
    assert imported == {"hashlib", "re"}, f"unexpected imports in the key derivation: {imported}"
